spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
      bindings:
#        greetings-in:
#          destination: greetings
#          contentType: application/json
        positions-out:
          destination: position
          contentType: application/json          
      
